name: Build

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - 'main'

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Build
        working-directory: .
        run: dotnet build .

      - name: Assign default GitHub URL base path
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          custom_domain=$(gh api "/repos/${{ github.repository }}/pages" | jq -r '.cname // empty')
          echo "CNAME config detected: $custom_domain"
          repo_name=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          org_name=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          if [ ! -f "./docs.unilake/wwwroot/CNAME" ] && [ -z "$custom_domain" ] 
          then
            echo "ssg_base_href=$(echo https://$org_name.github.io/$repo_name/)" 
            echo "ssg_base_href=$(echo https://$org_name.github.io/$repo_name/)" >> $GITHUB_ENV
          else
            if [ ! -z "$custom_domain" ]
            then
              echo "Persist CNAME '$custom_domain' to ./docs.unilake/wwwroot/CNAME"
              echo "$custom_domain" >> ./docs.unilake/wwwroot/CNAME
              echo "custom_domain=$custom_domain" >> $GITHUB_ENV
            fi
          fi

      - name: Build tailwind
        working-directory: ./src
        run: |
          npm run build

      - name: Prerender Site
        working-directory: ./src
        run: |
          site_base_href=${{ env.ssg_base_href }}
          site_base_url="https://${{ env.custom_domain }}"
          if [ ! -z "$site_base_href" ]
          then
            echo "Prerendering for deployment to $site_base_href"
            dotnet run --AppTasks=prerender --environment Production --BaseHref "$site_base_href"
          else
            echo "Prerendering for deployment to $custom_domain"
            dotnet run --AppTasks=prerender --environment Production --BaseUrl "$site_base_url"
          fi

      # Deploy UI to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5 
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4